<a href="https://colab.research.google.com/github/yoojinlee-hub/Practice_python/blob/main/numpy%20array%20%EC%97%B0%EC%82%B0%20%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array1=np.array([2,3,5,7,11,13,17,19,23,29,31])

인덱싱

In [3]:
array1[-1]

31

In [4]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [5]:
array2=np.array([2,1,3])
array1[array2]

array([5, 3, 7])

슬라이싱

In [6]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [7]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [8]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [10]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

numpy 기본연산

In [23]:
array1=np.arange(10)
array2=np.arange(10,20)

In [24]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
array1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
array1 **2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [28]:
array1=np.arange(10)
array2=np.arange(10,20)

In [29]:
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [30]:
array1*array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [31]:
array1/array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

신주쿠 흥부부대찌개

In [32]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
yen=np.array(revenue_in_yen) # 리스트를 numpy array로 바꾸기
won_array=yen*10.08
# 정답 출력
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

In [33]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.
yen=np.array(revenue_in_yen)
dollar=np.array(revenue_in_dollar)
won_array=yen*10.08+dollar*1138
# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

In [34]:
won_array.astype(int) #정수형으로 바꾸기

array([4389600, 5248000, 4818800, 5108200, 6825000, 3004400, 3521400,
       5817000, 5033400, 4630200, 5439800, 6220200, 4900000, 4370000,
       4253000, 5524400, 6421800, 6145400, 5651200, 3560400, 3612400,
       5150400, 6220200, 7016800, 5589400, 6623400, 3560400, 3814000,
       6018600, 5046400, 4568400])

numpy 불린 연산

In [35]:
import numpy as np
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [36]:
array1 > 4 #각 값을 비교

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [37]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [38]:
booleans = np.array([True,True,False,True,True,False,True,True,True,False,True])

In [39]:
np.where(booleans) #true 만 호출

(array([ 0,  1,  3,  4,  6,  7,  8, 10]),)

In [40]:
np.where(array1>4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [41]:
filter = np.where(array1>4) #필터링

In [42]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

흥부부대찌개 목표 일 매출

In [43]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
yen = np.array(revenue_in_yen)
filter =np.where(yen<=200000)
bad_days_revenue=yen[filter]
# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

In [44]:
import numpy as np #바로 인덱싱

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
yen = np.array(revenue_in_yen)
filter =np.where(yen<=200000)
bad_days_revenue=yen[filter]
# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])