In [2]:
import numpy
array1=numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [7]:
array2=numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
type(array2)

numpy.ndarray

In [10]:
array2.shape

(3, 4)

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
array1.size

11

In [13]:
array2.size

12

In [14]:
array3=numpy.full(6,7)

In [15]:
print(array3)

[7 7 7 7 7 7]


In [16]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)
    
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [17]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)
    
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [18]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
    
print(array1)
print()
print(array2)

[0.57229712 0.5152516  0.07185999 0.08497368 0.68628975 0.01586989]

[0.13054457 0.43453417 0.25201269 0.80975939 0.80938592 0.95626171]


In [19]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [20]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [21]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]
